const TripData = [
  {
    id: 1,
    title: "Plage de Nosy Be",
    image: "https://cdn.pixabay.com/photo/2019/11/04/14/37/madagascar-4601287_1280.jpg",
    description: "Découvrez la beauté de Nosy Be, une île paradisiaque de Madagascar, avec ses plages de sable blanc et ses eaux cristallines. Idéal pour les amateurs de plongée et de snorkeling.",
    price: 1500,
    duration: 7,
    highlights: [
      "Plongée sous-marine et snorkeling",
      "Excursions en bateau vers les îles voisines",
      "Visite de la réserve naturelle de Lokobe",
    ],
    gallery: [
      "https://example.com/images/nosybe-1.jpg",
      "https://example.com/images/nosybe-2.jpg",
      "https://example.com/images/nosybe-3.jpg",
    ],
    link: "/Nosy-Be",
  },
  {
    id: 2,
    title: "Tsingy de Bemaraha",
    image: "https://cdn.pixabay.com/photo/2019/11/04/14/37/madagascar-4601292_960_720.jpg",
    description: "Explorez les formations calcaires uniques des Tsingy de Bemaraha, un site classé au patrimoine mondial de l'UNESCO, offrant des paysages impressionnants et des aventures palpitantes.",
    price: 1800,
    duration: 5,
    highlights: [
      "Randonnée dans les gorges et les canyons",
      "Observation des animaux sauvages",
      "Vue panoramique depuis les passerelles suspendues",
    ],
    gallery: [
      "https://example.com/images/tsingy-1.jpg",
      "https://example.com/images/tsingy-2.jpg",
      "https://example.com/images/tsingy-3.jpg",
    ],
    link: "/Tsingy-de-Bemaraha",
  },
  {
    id: 3,
    title: "Avenue des Baobabs",
    image: "https://cdn.pixabay.com/photo/2022/02/13/10/06/boat-7010758_1280.jpg",
    description: "Marchez le long de l'avenue des Baobabs, l'une des routes les plus pittoresques de Madagascar, bordée par des baobabs géants et offrant des couchers de soleil à couper le souffle.",
    price: 1000,
    duration: 3,
    highlights: [
      "Photographie au coucher du soleil",
      "Rencontre avec les habitants locaux",
      "Découverte de la faune et de la flore locales",
    ],
    gallery: [
      "https://example.com/images/baobabs-1.jpg",
      "https://example.com/images/baobabs-2.jpg",
      "https://example.com/images/baobabs-3.jpg",
    ],
    link: "/Avenue-des-baobabs",
  },
  {
    id: 4,
    title: "Parc national d'Andasibe",
    image: "https://cdn.pixabay.com/photo/2019/10/29/15/30/madagascar-4587230_1280.jpg",
    description: "Visitez le parc national d'Andasibe, un paradis pour les amoureux de la nature, célèbre pour ses lémuriens, ses oiseaux rares et ses forêts tropicales luxuriantes.",
    price: 1200,
    duration: 4,
    highlights: [
      "Observation des lémuriens Indri-Indri",
      "Randonnée dans la forêt tropicale",
      "Visite nocturne pour observer les animaux nocturnes",
    ],
    gallery: [
      "https://example.com/images/andasibe-1.jpg",
      "https://example.com/images/andasibe-2.jpg",
      "https://example.com/images/andasibe-3.jpg",
    ],
    link: "/Andasibe",
  },
  {
    id: 5,
    title: "Île Sainte-Marie",
    image: "https://cdn.pixabay.com/photo/2019/11/01/17/39/maki-4594781_1280.jpg",
    description: "Détendez-vous sur l'île Sainte-Marie, une île idyllique au large de la côte est de Madagascar, connue pour ses plages immaculées, ses eaux turquoise et ses plongées avec les baleines.",
    price: 2000,
    duration: 7,
    highlights: [
      "Observation des baleines",
      "Plongée en apnée et plongée sous-marine",
      "Exploration des épaves de navires",
    ],
    gallery: [
      "https://example.com/images/sainte-marie-1.jpg",
      "https://example.com/images/sainte-marie-2.jpg",
      "https://example.com/images/sainte-marie-3.jpg",
    ],
    link: "/sainte-marie",
  },
  {
    id: 6,
    title: "Parc national de l'Isalo",
    image: "https://cdn.pixabay.com/photo/2019/11/02/21/39/child-4597491_1280.jpg",
    description: "Découvrez le parc national de l'Isalo, célèbre pour ses formations rocheuses spectaculaires, ses canyons profonds et ses piscines naturelles idéales pour la baignade.",
    price: 1600,
    duration: 5,
    highlights: [
      "Randonnée dans les canyons de l'Isalo",
      "Baignade dans les piscines naturelles",
      "Observation des oiseaux et des lémuriens",
    ],
    gallery: [
      "https://example.com/images/isalo-1.jpg",
      "https://example.com/images/isalo-2.jpg",
      "https://example.com/images/isalo-3.jpg",
    ],
    link: "/isalo",
  },
  {
    id: 7,
    title: "Rivière Tsiribihina",
    image: "https://cdn.pixabay.com/photo/2015/11/24/19/10/animals-1060604_1280.jpg",
    description: "Partez à l'aventure sur la rivière Tsiribihina, un voyage en bateau fascinant à travers les gorges profondes, les cascades et la faune sauvage de Madagascar.",
    price: 1400,
    duration: 4,
    highlights: [
      "Excursion en bateau sur la rivière",
      "Observation des crocodiles et des oiseaux",
      "Cascades et baignades",
    ],
    gallery: [
      "https://example.com/images/tsiribihina-1.jpg",
      "https://example.com/images/tsiribihina-2.jpg",
      "https://example.com/images/tsiribihina-3.jpg",
    ],
    link: "/tsiribihina",
  },
  {
    id: 8,
    title: "Montagne d'Ambre",
    image: "https://cdn.pixabay.com/photo/2015/02/16/16/20/lizard-638493_1280.jpg",
    description: "Explorez la montagne d'Ambre, une région volcanique riche en biodiversité, avec des forêts tropicales, des cascades et des lacs de cratère.",
    price: 1300,
    duration: 3,
    highlights: [
      "Randonnée à travers les forêts tropicales",
      "Visite des lacs de cratère",
      "Observation de la faune et de la flore locales",
    ],
    gallery: [
      "https://example.com/images/amber-mountain-1.jpg",
      "https://example.com/images/amber-mountain-2.jpg",
      "https://example.com/images/amber-mountain-3.jpg",
    ],
    link: "/Montagne-d-Ambre",
  },
  {
    id: 9,
    title: "Ifaty",
    image: "https://cdn.pixabay.com/photo/2020/04/11/15/31/baobab-5030877_1280.jpg",
    description: "Profitez des plages de sable fin et des eaux calmes d'Ifaty, un lieu idéal pour la détente, la plongée avec tuba et la découverte des récifs coralliens.",
    price: 1100,
    duration: 3,
    highlights: [
      "Snorkeling et plongée sur les récifs coralliens",
      "Promenade en pirogue traditionnelle",
      "Observation des oiseaux et de la vie marine",
    ],
    gallery: [
      "https://example.com/images/ifaty-1.jpg",
      "https://example.com/images/ifaty-2.jpg",
      "https://example.com/images/ifaty-3.jpg",
    ],
    link: "/ifaty",
  },
  {
    id: 10,
    title: "Diego-Suarez",
    image: "https://cdn.pixabay.com/photo/2013/02/15/13/29/madagascar-81894_1280.jpg",
    description: "Découvrez Diego-Suarez, une ville portuaire animée avec une riche histoire, de belles plages et une base idéale pour explorer le nord de Madagascar.",
    price: 1700,
    duration: 6,
    highlights: [
      "Visite du pain de sucre",
      "Excursion à la mer d'émeraude",
      "Découverte de la culture locale et de la cuisine",
    ],
    gallery: [
      "https://example.com/images/diego-suarez-1.jpg",
      "https://example.com/images/diego-suarez-2.jpg",
      "https://example.com/images/diego-suarez-3.jpg",
    ],
    link: "Diego-suarez",
  },
];

export default TripData;
